
public static final Animation JUMP = Animation.Builder.create(1f)
.addBoneAnimation("body",
	new Transformation(Transformation.Targets.TRANSLATE, 
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
			Transformation.Interpolations.LINEAR), 
		new Keyframe(0.125f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
			Transformation.Interpolations.LINEAR), 
		new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
			Transformation.Interpolations.LINEAR), 
		new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
			Transformation.Interpolations.LINEAR), 
		new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
			Transformation.Interpolations.LINEAR)))
.addBoneAnimation("body",
	new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
			Transformation.Interpolations.LINEAR),
		new Keyframe(0.125f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
			Transformation.Interpolations.LINEAR),
		new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
			Transformation.Interpolations.LINEAR),
		new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
			Transformation.Interpolations.LINEAR),
		new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
			Transformation.Interpolations.LINEAR)))
.addBoneAnimation("body",
	new Transformation(Transformation.Targets.SCALE,
		new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
			Transformation.Interpolations.LINEAR),
		new Keyframe(0.125f, AnimationHelper.createScalingVector(1.15f, 1.15f, 1.15f),
			Transformation.Interpolations.LINEAR),
		new Keyframe(0.25f, AnimationHelper.createScalingVector(1.3f, 1.3f, 1.3f),
			Transformation.Interpolations.LINEAR),
		new Keyframe(0.375f, AnimationHelper.createScalingVector(1.15f, 1.15f, 1.15f),
			Transformation.Interpolations.LINEAR),
		new Keyframe(0.5f, AnimationHelper.createScalingVector(1f, 1f, 1f),
			Transformation.Interpolations.LINEAR))).build();